//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-05/12/2011 11:54 AM(foreman)-)
//


package com.webage.billing.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "addAccountResponse", namespace = "http://billing.webage.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addAccountResponse", namespace = "http://billing.webage.com/")
public class AddAccountResponse {

    @XmlElement(name = "status", namespace = "")
    private String status;

    /**
     * 
     * @return
     *     returns String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 
     * @param status
     *     the value for the status property
     */
    public void setStatus(String status) {
        this.status = status;
    }

}
