//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-05/12/2011 11:54 AM(foreman)-)
//


package com.webage.billing.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "addAccount", namespace = "http://billing.webage.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addAccount", namespace = "http://billing.webage.com/")
public class AddAccount {

    @XmlElement(name = "account", namespace = "")
    private com.webage.billing.CustomerAccount account;

    /**
     * 
     * @return
     *     returns CustomerAccount
     */
    public com.webage.billing.CustomerAccount getAccount() {
        return this.account;
    }

    /**
     * 
     * @param account
     *     the value for the account property
     */
    public void setAccount(com.webage.billing.CustomerAccount account) {
        this.account = account;
    }

}
