//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.webage.billing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "BillingManager", targetNamespace = "http://billing.webage.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillingManager {


    /**
     * 
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "addAccount", targetNamespace = "http://billing.webage.com/", className = "com.webage.billing.AddAccount")
    @ResponseWrapper(localName = "addAccountResponse", targetNamespace = "http://billing.webage.com/", className = "com.webage.billing.AddAccountResponse")
    public String addAccount(
        @WebParam(name = "account", targetNamespace = "")
        CustomerAccount account);

}
