//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.webage.billing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "BillingManagerService", targetNamespace = "http://billing.webage.com/", wsdlLocation = "WEB-INF/wsdl/BillingManagerService.wsdl")
public class BillingManagerService
    extends Service
{

    private final static URL BILLINGMANAGERSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:./WEB-INF/wsdl/BillingManagerService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BILLINGMANAGERSERVICE_WSDL_LOCATION = url;
    }

    public BillingManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingManagerService() {
        super(BILLINGMANAGERSERVICE_WSDL_LOCATION, new QName("http://billing.webage.com/", "BillingManagerService"));
    }

    /**
     * 
     * @return
     *     returns BillingManager
     */
    @WebEndpoint(name = "BillingManagerPort")
    public BillingManager getBillingManagerPort() {
        return (BillingManager)super.getPort(new QName("http://billing.webage.com/", "BillingManagerPort"), BillingManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingManager
     */
    @WebEndpoint(name = "BillingManagerPort")
    public BillingManager getBillingManagerPort(WebServiceFeature... features) {
        return (BillingManager)super.getPort(new QName("http://billing.webage.com/", "BillingManagerPort"), BillingManager.class, features);
    }

}
