<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" name="MovieService" targetNamespace="http://www.mycom.com/movie" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.mycom.com/movie" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://www.mycom.com/movie" schemaLocation="MovieService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="addMovieResponse">
    <part element="tns:addMovieResponse" name="parameters">
    </part>
  </message>
  <message name="addMovie">
    <part element="tns:addMovie" name="parameters">
    </part>
  </message>
  <portType name="movie_service">
    <operation name="addMovie">
      <input message="tns:addMovie" wsam:Action="http://www.mycom.com/movie/NewOperation">
    </input>
      <output message="tns:addMovieResponse" wsam:Action="http://www.mycom.com/movie/movie_service/addMovieResponse">
    </output>
    </operation>
  </portType>
  <binding name="MovieServiceSOAPPortBinding" type="tns:movie_service">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="addMovie">
      <soap:operation soapAction="http://www.mycom.com/movie/NewOperation"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MovieService">
    <port binding="tns:MovieServiceSOAPPortBinding" name="MovieServiceSOAPPort">
      <soap:address location="http://localhost:9080/WebServiceProjectWAR/MovieService"/>
    </port>
  </service>
</definitions>