<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" name="OrderSoupService" targetNamespace="http://ejb.webage.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ejb.webage.com/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://ejb.webage.com/" schemaLocation="OrderSoupService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="BadCustomerException">
    <part element="tns:BadCustomer" name="fault">
    </part>
  </message>
  <message name="orderSoup">
    <part element="tns:orderSoup" name="parameters">
    </part>
  </message>
  <message name="orderSoupResponse">
    <part element="tns:orderSoupResponse" name="parameters">
    </part>
  </message>
  <portType name="OrderSoup">
    <operation name="orderSoup">
      <input message="tns:orderSoup" wsam:Action="http://ejb.webage.com/OrderSoup/orderSoupRequest">
    </input>
      <output message="tns:orderSoupResponse" wsam:Action="http://ejb.webage.com/OrderSoup/orderSoupResponse">
    </output>
      <fault message="tns:BadCustomerException" name="BadCustomerException" wsam:Action="http://ejb.webage.com/OrderSoup/orderSoup/Fault/BadCustomerException">
    </fault>
    </operation>
  </portType>
  <binding name="OrderSoupPortBinding" type="tns:OrderSoup">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="orderSoup">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="BadCustomerException">
        <soap:fault name="BadCustomerException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="OrderSoupService">
    <port binding="tns:OrderSoupPortBinding" name="OrderSoupPort">
      <soap:address location="http://localhost:9085/EJBService_HTTPRouter/OrderSoupService"/>
    </port>
  </service>
</definitions>